openapi: 3.0.1
info:
  title: StockQuote
  description: API Definition of StockQuote
  version: 1.0.0
servers:
- url: http://localhost:8290/stockquotepost
paths:
  /:
    get:
      responses:
        default:
          description: Default response
